<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>ImageToWebpConverter</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\appicon.ico</ApplicationIcon>

    <Company>NicolasK98</Company>
    <Authors>Nicolas Kovac</Authors>
    <Product>Convertitore Image in WebP</Product>
    <Description>Strumento batch per la conversione rapida di immagini in formato WebP.</Description>
    <Copyright>Copyright © 2026 Nicolas Kovac</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>

    <Platform>x64</Platform>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWinUI>true</UseWinUI>
    <Nullable>enable</Nullable>

    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <SelfContained>true</SelfContained>
    <EnableMsixTooling>true</EnableMsixTooling>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

    <GenerateAppxPackageOnBuild>false</GenerateAppxPackageOnBuild>
    <AppxPackage>false</AppxPackage>
    <DisableMsixProjectCapabilityAddedByProject>false</DisableMsixProjectCapabilityAddedByProject>
    <AppxGeneratePriEnabled>true</AppxGeneratePriEnabled>
  </PropertyGroup>
  
  <ItemGroup>
    <None Remove="Assets\appicon-128.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\StoreLogo.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Magick.NET-Q8-x64" Version="14.16.0" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
    <PackageReference Include="WinUIEx" Version="2.9.3" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="Assets\appicon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Update="Assets\appicon-128.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <None Update="Assets\appicon.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>

  <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun>false</PublishReadyToRun>
    <PublishTrimmed>false</PublishTrimmed>
    <ApplicationIcon>Assets\appicon.ico</ApplicationIcon>
    <PackageIcon>appicon-128.png</PackageIcon>
  </PropertyGroup>

  <Target Name="CopyResourcesPri" AfterTargets="Publish">
    <ItemGroup>
      <_PriFiles Include="$(OutputPath)resources.pri" Condition="Exists('$(OutputPath)resources.pri')" />
      <_PriFiles Include="$(ProjectDir)resources.pri" Condition="Exists('$(ProjectDir)resources.pri')" />
    </ItemGroup>
    <Copy SourceFiles="@(_PriFiles)"
          DestinationFolder="$(PublishDir)"
          SkipUnchangedFiles="true"
          Condition="'@(_PriFiles)' != ''" />
  </Target>
</Project>